### ISSUE TITLE
Q. about the preprocess of Data

### ISSUE THREAD

**Issue by isbada** [aelnouby/Text-to-Image-Synthesis#12]
Hi, @aelnouby 
     Thank you for your sharing.
     In the process of getting data, I want to Convert the data by myself, so I download the dataset  as the describe of https://github.com/reedscot/cvpr2016 , then I got a link (flowers , for example) https://drive.google.com/open?id=0B0ywwgffWnLLcms2WWJQRFNSWXM and download a file named **cvpr2016_flowers.tar.gz** , then I unzipped  it and the unzipped folder looked like following 
![image](https://user-images.githubusercontent.com/23022062/35625504-8d87f708-06cd-11e8-9094-4dca144afa79.png)
     I can't understand how you organized your file to excute the script  **'convert_flowers_to_hd5_script.py'**  correctly . Did I download a wrong file ? 
     Looking forward your reply!

**Comment by aelnouby** [comment]
Hi,

Have you checked the `config.yaml` file ?
