### ISSUE TITLE
Manifold interpolation

### ISSUE THREAD

**Issue by ashual** [aelnouby/Text-to-Image-Synthesis#17]
In the original paper, the authors show that their manifold interpolation gets a big improvement. Did you implement this part in your code?

**Comment by aelnouby** [comment]
The training code does not include this part. However the dataset code support this https://github.com/aelnouby/Text-to-Image-Synthesis/blob/f6d47e4da06defa974390ce813f734dbee75c885/txt2image_dataset.py#L58 

One of the dataset class return values is the interpolation embeddings which is the embedding of another random example. You can use it to implement this part in the paper, it should be straight forward.

**Comment by ashual** [comment]
Thanks
