### ISSUE TITLE
Release models for Flowers, Birds and COCO datasets

### ISSUE THREAD

**Issue by sriharsha-sammeta** [aelnouby/Text-to-Image-Synthesis#19]
Hi,

Can you please release pre-trained models for all 3 datasets ?

**Comment by aelnouby** [comment]
I have not trained this model on COCO, I am currently busy with other projects.

I am always welcoming pull requests, you can follow the same procedure I did with the first datasets with COCO, it will be great if you can add this to the repo.

I also encourage you to check more recent GAN architectures like StackGAN, AttnGAN I believe they produce significantly better results than this paper but they are also a little more complicated.

Good luck !

**Comment by sriharsha-sammeta** [comment]
Thank you for the response. Can you please release the models for Flowers and Birds if you have them?

**Comment by aelnouby** [comment]
@sriharsha-sammeta  First if all I don't appreciate you copying my code to your own repo instead of forking !!

I did not save the models, I used the same hyperparams as in the code so it is only matter of running the code.

**Comment by sriharsha-sammeta** [comment]
@aelnouby , sorry for that. I cloned your repo, fiddled around with it like changing some parameters in the code. In the rush to push it google cloud for training, I quickly pushed it to my repo so that I can clone it back into my vm in google cloud. 

Sorry again for that. I have deleted the repo now. I will fork it and make the changes here after. 

I was running it on birds dataset and I have already trained it for around 2800 epochs now but still I dont see the model converging. Hence, asked for pre-trained models.

**Comment by aelnouby** [comment]
As far as I remember I could not get the birds dataset to get very good generations, they were not as convincing as the flowers so I guess the behaviour you are seeing is normal. Again I suggest you check stackGAN and AttnGAN, they have better generations than this paper.

**Comment by sriharsha-sammeta** [comment]
ok. Thank you. Do you think trying with your WGAN can probably give a better result on birds dataset? Because I don't really know stackGAN or AttnGAN. So it will be difficult to implement them now.

**Comment by aelnouby** [comment]
It can possibly give an improvement. 

For stackGAN there are ope-source code here https://github.com/hanzhanggit/StackGAN-Pytorch

**Comment by sriharsha-sammeta** [comment]
oh ok. I will follow that. Thanks again.
