### ISSUE TITLE
Duplicate embeddings in convert_cub_to_hd5_script.py 

### ISSUE THREAD

**Issue by pratch** [aelnouby/Text-to-Image-Synthesis#25]
As I was reading `convert_cub_to_hd5_script.py` to get a better understanding of the .hdf5 structure, I came across this line:

`txt_choice = np.random.choice(range(10), 5)`

where five text embeddings are supposedly randomly sampled. However, by default, `np.random.choice` does sampling *with* replacement, which in this case could cause the same embedding to be picked twice. Would this be an issue?

**Comment by aelnouby** [comment]
Good catch ! 

I think this issue might cause training to take longer to get to a good point but it should get there eventually. I will fix this now. Thanks.
