### ISSUE TITLE
What is the file of text embeddings?

### ISSUE THREAD

**Issue by Hanzy1996** [aelnouby/Text-to-Image-Synthesis#28]
Do you mean the text embedding is text encoders for [birds](https://drive.google.com/open?id=0B0ywwgffWnLLU0F3UHA3NzFTNEE) and [flowers](https://drive.google.com/open?id=0B0ywwgffWnLLZUt0UmQ1LU1oWlU)? And how to use these two .t7 files?

Thanks a lot.

**Comment by aelnouby** [comment]
The extracted embeddings are already stored in the HDF5 files.

**Comment by Hanzy1996** [comment]
Thank you very much! It works well.
