### ISSUE TITLE
Can't find the file:"text_c10"

### ISSUE THREAD

**Issue by coderSkyChen** [aelnouby/Text-to-Image-Synthesis#4]
Hi, I'm learning text-to-image, and thanks a lot for your reimplement in pytorch!
However, i can not find the text_c10 files for birds and flowers dataset, is it the descriptions of the image?
It looks like the author of the icml2016 have not provide the original descriptions but the text embedding in torch format.

Watting for your reply.

**Comment by aelnouby** [comment]
Hi, 

You can find the text embedding data here https://github.com/reedscot/cvpr2016, this the implementation of an earlier paper from the same authors where they introduced the char-RNN-CNN text encoding model.

You can also download the converted hd5 files (links on readme) and use them directly.

**Comment by coderSkyChen** [comment]
Ok， thanks a lot!
